version: '3.8'

services:
  openrouter-email:
    build: .
    image: openrouter-email:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - OPENROUTER_TOKEN=${OPENROUTER_TOKEN}
      - EMAILPROVIDER_TOKEN=${EMAILPROVIDER_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3

  openrouter-email-native:
    profiles: ["native"]
    build:
      context: .
      target: native
    image: openrouter-email-native:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - OPENROUTER_TOKEN=${OPENROUTER_TOKEN}
      - EMAILPROVIDER_TOKEN=${EMAILPROVIDER_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
